# Copyright (c) 20225 b»robotized Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

b_controlled_box_cm:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    kassow_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kassow_left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    kassow_right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kassow_gpio_controller:
      type: gpio_controllers/GpioCommandController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster


kassow_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    update_rate: 250  # Hz
    joints:
      - kassow_joint_1
      - kassow_joint_2
      - kassow_joint_3
      - kassow_joint_4
      - kassow_joint_5
      - kassow_joint_6
      - kassow_joint_7

    command_interfaces:
      - position
      - velocity
      - acceleration

    state_interfaces:
      - position
      - velocity
      - acceleration

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)


kassow_left_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    update_rate: 250  # Hz
    joints:
      - kassow_left_joint_1
      - kassow_left_joint_2
      - kassow_left_joint_3
      - kassow_left_joint_4
      - kassow_left_joint_5
      - kassow_left_joint_6
      - kassow_left_joint_7

    command_interfaces:
      - position
      - velocity
      - acceleration

    state_interfaces:
      - position
      - velocity
      - acceleration

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

kassow_right_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    update_rate: 250  # Hz
    joints:
      - kassow_right_joint_1
      - kassow_right_joint_2
      - kassow_right_joint_3
      - kassow_right_joint_4
      - kassow_right_joint_5
      - kassow_right_joint_6
      - kassow_right_joint_7

    command_interfaces:
      - position
      - velocity
      - acceleration

    state_interfaces:
      - position
      - velocity
      - acceleration

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)


kassow_gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - kassow_digital_IOs

    command_interfaces: # OUTPUTS we can control
      kassow_digital_IOs:
        - interfaces:
          - kassow_RELAY_1
          - kassow_RELAY_2
          - kassow_RELAY_3
          - kassow_RELAY_4
          - kassow_DO_1
          - kassow_DO_2
          - kassow_DO_3
          - kassow_DO_4
          - kassow_DO_5
          - kassow_DO_6
          - kassow_DO_7
          - kassow_DO_8
          - kassow_TB_1
          - kassow_TB_2
          - kassow_TB_3
          - kassow_TB_4

    state_interfaces:
      kassow_digital_IOs:
        - interfaces:
          - kassow_RELAY_1
          - kassow_RELAY_2
          - kassow_RELAY_3
          - kassow_RELAY_4
          - kassow_DO_1
          - kassow_DO_2
          - kassow_DO_3
          - kassow_DO_4
          - kassow_DO_5
          - kassow_DO_6
          - kassow_DO_7
          - kassow_DO_8
          - kassow_TB_1
          - kassow_TB_2
          - kassow_TB_3
          - kassow_TB_4
          - kassow_DI_1
          - kassow_DI_2
          - kassow_DI_3
          - kassow_DI_4
          - kassow_DI_5
          - kassow_DI_6
          - kassow_DI_7
          - kassow_DI_8
          - kassow_DI_9
          - kassow_DI_10
          - kassow_DI_11
          - kassow_DI_12
          - kassow_DI_13
          - kassow_DI_14
          - kassow_DI_15
          - kassow_DI_16
