/**:
  ros__parameters:
    pilz:
      planning_plugins: [pilz_industrial_motion_planner/CommandPlanner]
      default_planner_config: PTP
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateBounds
        - default_planning_request_adapters/CheckStartStateCollision
        - cubic_spline_smoothing_adapter/CubicSplineSmoothingAdapter
      response_adapters:
        - default_planning_response_adapters/ValidateSolution
        - default_planning_response_adapters/DisplayMotionPath

      capabilities: >-
        pilz_industrial_motion_planner/MoveGroupSequenceAction
        pilz_industrial_motion_planner/MoveGroupSequenceService

      path_dev_max: 0.05
      pos_tol: 0.01
      max_time_stretch: 1.50
      seam_eps: 1e-5
